FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY frontend/package.json ./frontend/package.json
COPY backend/package.json ./backend/package.json
COPY workers/package.json ./workers/package.json
RUN npm ci --workspaces --include-workspace-root

COPY . .
WORKDIR /app/workers

ENV NODE_ENV=production
ENV WORKER_ENTRY=worker.js
CMD ["sh", "-c", "node ${WORKER_ENTRY}"]
