export function buildCleanupPrompt(transcriptText) {
  return `You are cleaning a YouTube lecture transcript for downstream retrieval.\n\nTasks:\n- Fix obvious transcription errors\n- Remove filler words when they do not add meaning\n- Preserve all important facts, examples, and definitions\n- Keep timestamps or sequence hints implied in the wording\n\nTranscript:\n${transcriptText}`;
}

export function buildConceptExtractionPrompt(chunkText) {
  return `Analyze this lecture chunk and produce:\n1. A crisp summary\n2. Core concepts\n3. Important examples\n4. Misconceptions or caveats\n\nChunk:\n${chunkText}\n\nReturn JSON with keys summary, concepts, examples, caveats.`;
}

export function buildFinalNotesPrompt({ title, transcriptSummary, concepts, retrievedContext }) {
  return `You are an expert academic note creator. Convert the lecture transcript into professional structured study notes formatted like a polished Notion page.\n\nRequired sections:\n1. Title\n2. Overview\n3. Key Concepts\n4. Detailed Explanation\n5. Important Points\n6. Concept Table\n7. Examples\n8. Key Takeaways\n9. Practice Questions\n10. Flashcards\n11. Quiz\n12. Timestamped Notes\n13. Topic Preview\n\nOptional section:\n- Visual Diagram\n\nRules:\n- Use Markdown headings\n- Use bullet points when they improve readability\n- Use tables\n- Use callout blocks using markdown quote syntax\n- Write clear educational explanations\n- Focus on study quality, not short summarization\n- Make Detailed Explanation the teaching core of the notes\n- In Detailed Explanation, do not write only topic names, headings, or short fragments\n- For each major idea, explain what it means, why it matters, and how it works in simple student-friendly language\n- Each Detailed Explanation item should be a rich explanation of 2-4 full sentences\n- When helpful, add a short example, analogy, or comparison so a beginner can understand the idea quickly\n- Add visualDiagram only when the topic genuinely benefits from a diagram such as a process, system flow, dependency map, cause-and-effect chain, hierarchy, or comparison\n- If the topic does not need a helpful diagram, return visualDiagram as an empty string or \"No diagram generated.\"\n- When a diagram is included, it must be a real Mermaid flow diagram, not plain text bullets or a list of topics\n- topicPreview must be an array of 3 to 5 short explainer cards\n- Each topicPreview item must contain title, narration, and takeaway\n- narration should sound like a simple teaching script for a quick AI explainer video\n- Include timestamps when the context provides them\n\nVideo title: ${title}\n\nTranscript understanding:\n${transcriptSummary}\n\nExtracted concepts:\n${JSON.stringify(concepts, null, 2)}\n\nRetrieved high-signal context:\n${retrievedContext}\n\nReturn strict JSON with keys:\ntitle, overview, keyConcepts, detailedExplanation, importantPoints, conceptTable, visualDiagram, examples, keyTakeaways, practiceQuestions, flashcards, quiz, timestampedNotes, topicPreview.`;
}

export function buildQuestionAnswerPrompt({ question, context, title }) {
  return `You are answering a student's question about a YouTube lecture.\n\nVideo title: ${title}\nQuestion: ${question}\n\nUse the context below to answer accurately. If the answer is uncertain, say what is supported by the transcript. Include a short bullet list of evidence.\n\nContext:\n${context}`;
}
